const poems = [
	{
		title: 'Abandoned',
		lines: [
			'Where am I? I know not',
			'The way back home, I forgot',
			'Is this my reward for loyalty?',
			'All the love and care just empty?',
			'',
			'I miss those hugs, miss that food',
			'The people are here are not so good',
			'Trash is what fills my stomach',
			"With heartless creatures, I'm stuck.",
			'',
			'Pipes and footpath as my bed',
			'All I have is tears to shed',
			'Nights of comfort now deprived',
			'Living the days only terrified.',
			'',
			'Just a rumour that you hear',
			'Made you abandon me forever',
			'I wait to be called by my name',
			"Won't things ever be the same?",
			'',
			'Am I still your Oscar',
			'Or just a random dog here?',
			'Will I ever again get love',
			'Or forever be a trivial bhow?',
		],
		imgSrc: 'images/abandoned.jpg',
		imgAltText: 'dog image',
		date: '2020-05',
	},
	{
		title: 'Deceiving Flower',
		lines: [
			'In this land of thorns',
			'Full of grief and full of mourns',
			'You bloomed like a flower',
			'Was it love and care to shower?',
			'',
			'Like a flower to a bee',
			'You were more than that to me',
			'Like flowers for the altar',
			'You always adorned my prayer',
			'',
			'I watered you day and night',
			'Only expected to be treated right',
			'Petals that seemed arms of love',
			'Are brutal swords of anguish now',
			'',
			'You used and abused and left me',
			'Now not even thorns to protect me',
			'The beautiful flower I thought you were',
			"Ended up decorating my soul's grave",
		],
		imgSrc: 'images/deceivingflower.jpg',
		imgAltText: 'flower image',
		date: '2019-07',
	},
	{
		title: 'Nightmare',
		lines: [
			'At the dawn',
			'I still had yawn',
			'The night so deep',
			'But still no sleep',
			'',
			'Thoughts that came',
			'Drove me insane',
			'You would be there',
			'But not in my air',
			'',
			'You would sing',
			'And give her the ring',
			'But what if that she',
			"Wouldn't be me",
			'',
			'The anxiety flew',
			"Coz it wasn't true",
			'You are mine',
			'And me forever thine',
		],
		imgSrc: 'images/nightmare.jpg',
		imgAltText: 'moon image',
		date: '2019-06',
	},
	{
		title: 'She',
		lines: [
			'All she needs is',
			'Not power, not authority, not sympathy.',
			'A life that isnt controlled by the thoughts of the society.',
			'A life that doesnt objectify us.',
			'A life that isnt suppressed for the honour of the family.',
			'A life that isnt considered a burden for anyone.',
			'A life that isnt mocked continuously.',
			'A life with equal opportunities.',
			'A life having the freedom to fly high.',
			'A life that is secure at all times of the day.',
			'All she needs is a life with just the right amount of respect!',
		],
		imgSrc: 'images/she.jpg',
		imgAltText: 'picture of a girl',
		date: '2021-02',
	},
	{
		title: 'What if I say',
		lines: [
			'What if I say,',
			'I was broken when you left',
			'Day and night I had wept',
			'My soul is what you tore',
			"But still I'll love you more",
			'',
			'What if I say,',
			'I still wait for your call',
			'Search my peace in alcohol',
			'Self worth burnt to cinder',
			'But will care for you forever',
			'',
			'What if I say,',
			"Living without you, I can't",
			'I will be the way you want',
			'Will always give you plenty',
			"Even though right now I'm empty",
			'',
			'Then will you,',
			'Come back to me',
			'And set my achy soul free',
			'Love and respect me just a little',
			"And never break my heart that's brittle?",
		],
		imgSrc: 'images/whatif.jpg',
		imgAltText: 'broken glass',
		date: '2020-04',
	},
	{
		title: 'Friend',
		lines: [
			"I know you feel 'Lost'",
			"Thoughts like 'What I've done'",
			"With a 'faint' idea of what's yet to come",
			"All good memories 'forgotten'",
			"Negative thoughts 'crawling' in your head",
			"With positivity being 'invisible'",
			"But 'in the end'",
			"You are going to win this 'war'",
			"'Roads untravelled' always bring fear",
			"Just know that you are 'halfway right'",
			"I know it is always 'easier to run'",
			"But you are not someone who would 'runaway'",
			"So all the doubts, just 'burn it down'",
			"Negativity, just 'bleed it out'",
			"Soon there will be 'no more sorrow'",
			"And you will 'wake' up to a better tomorrow",
			"It does feel 'heavy' 'from the inside'",
			"But 'don't stay' in this gloominess",
			"There is no choice to have 'given up'",
			"The 'rebellion' in you will have to revolt",
			"Just take 'one step closer'",
			"Towards 'the radiance' of hope",
			"Fight with 'hands held high' 'until it's gone'",
			"Don't forget you are 'not alone'",
			"It might feel like 'nobody's listening'",
			"But remember, I'm always there 'with you'",
		],
		imgSrc: 'images/friend.jpg',
		imgAltText: 'handshake',
		date: '2023-05',
	},
	{
		title: 'Fate',
		lines: [
			'Questions is what remains',
			'With no answers at all',
			'Fate having its own way',
			'Demanding to surrender it all',
			'Reminding that mere humans',
			'Have no powers at all',
		],
		imgSrc: 'images/fate.jpg',
		imgAltText: 'question mark',
		date: '2020-06',
	},
	{
		title: 'Yearn',
		lines: [
			'The stars, the coffee, the chorus',
			'Why is nothing the same',
			'Is it within us or between us',
			'That something has changed',
			'',
			'The one I search in your eyes is lost',
			'The one in the mirror is now unfound',
			'Someone who meant the world to me',
			'Now just breathes on this earth guilt free',
			'',
			'People change with time they say',
			'Come in your life to just walk away',
			'The good morning that started my day',
			'Is now said in a formal way',
			'',
			'We cross paths with awkward smiles',
			'Once promised to walk together miles',
			'All I have with memories bittersweet',
			'Is a desire we never meet',
		],
		imgSrc: 'images/yearn.jpg',
		imgAltText: 'yearn',
		date: '2023-11',
	},
	{
		title: 'The Season of Joy',
		lines: [
			"It's Christmas mate",
			'No place for hate',
			'Lying in the manger, humble and meek',
			"Declaring, kindness doesn't mean you're weak.",
			'',
			'Came for me, came for you',
			'Showering love that is pure and true',
			"O child, give and don't expect",
			'Is the message of this Advent.',
			'',
			'Love self and give love to all',
			'Bitterness just deprives peace afterall',
			'To forgive and redeem everyone',
			"Came to earth, God's only son!",
		],
		imgSrc: 'images/seasonofjoy.jpg',
		imgAltText: 'christmas image',
		date: '2023-12',
	},
        {
                title: 'I stand on this road',
                lines: [
                        'I stand on this road',
                        'With cars honking loud',
                        'In a hurry to go',
                        'But dogs crossing slow.',
                        '',
                        'I stand on this road',
                        'With kids moving around',
                        'Playing and laughing',
                        'Falling without worrying.',
                        '',
                        'I stand on this road',
                        'With a man crying alone',
                        'Longing for a shoulder',
                        'Worried about his future.',
                        '',
                        'I stand on this road',
                        'With lovers holding hands',
                        'Exchanging promises of love',
                        'Witness being the sky above.',
                        '',
                        'I stand on this road',
                        'Amidst these emotions',
                        'Confused about my own',
                        'Walking on a path unknown.',

                ],
                imgSrc: 'images/deceivingflower.jpg',
                imgAltText: 'road image',
                date: '2024-04',
        },
];
